server:
  port: 3001
spring:
  application:
    name: spring-boot-mybatis-interceptor
  profiles:
    active: dev

#配置日志-使用外部配置文件
logging:
  config: classpath:logback-spring.xml

#jasypt加密
jasypt:
  encryptor:
    password: PFqEQomIp=
